### PR TITLE
feature/stdcpp-static

### PR DESCRIPTION
**Pull request by dsvost**
ProofOfSpace target static build

### CODE REVIEW

**Comment by SkycoinSynth** [comment]
Conflict. Fix conflict.

**Comment by SkycoinSynth** [comment]
```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static")
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -static")
```

Should be "-gcc-static" because there is another ticket for static builds against musl

**Comment by Sameeranjoshi** [comment]
I think something is wrong with this commit.
This is causing me failure in building the project with the steps mentioned in README.md with this commit.
```
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libm-2.27.a
collect2: error: ld returned 1 exit status
CMakeFiles/ProofOfSpace.dir/build.make:206: recipe for target 'ProofOfSpace' failed
make[2]: *** [ProofOfSpace] Error 1
CMakeFiles/Makefile2:184: recipe for target 'CMakeFiles/ProofOfSpace.dir/all' failed
make[1]: *** [CMakeFiles/ProofOfSpace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

I didn't test this option before and this took much of bandwidth in figuring that if I was doing something wrong for compiling for xenial.
I was searching the internet a lot for solving the xenial issue, but the problem seems with this commit.
The answer at [1] which adds options below seems to be helpful to solve the xenial issue
`-Wl,--rpath=${glibc_install}/lib -Wl,--dynamic-linker=${glibc_install}/lib/ld-linux-x86-64.so.2`

Any comments/suggestions @SkycoinSynth ?

[1] https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version

**Comment by Sameeranjoshi** [comment]
Can the original author of this patch fix this?

**Comment by dsvost** [comment]
It builds successfully on Ubuntu 20.04. There is just one addition in this branch to make it statically link everything. The key `-static` added to all `gcc` and `g++` invokes by cmake as a result of it. This key just instruct gcc refuse all shared libraries and statically link everything. So, the error message you have says that your system has not a static version of `libm`. On Ubuntu 20.04 static version of it can be installed with package `libc6-dev` and on other systems the appropriate package exists. Also, to be able see how actually cmake call gcc/g++ and what parameters it pass to them and see more useful output VERBOSE environment variable can be used, like this (inside cmake build directory):`VERBOSE=1 make -j$(nproc)`.

**Comment by Sameeranjoshi** [comment]
Your right.
I had the library but then I symlinked it and it solved the issue.
Thank you.

**Comment by Kayuii** [comment]
Dockerfile 
```
FROM ubuntu:20.04 as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y

RUN apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  git \
  python3 \
  python3-dev \
  python3-distutils \
  libc6-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN mkdir -p build

WORKDIR /app/build
RUN cmake -DBUILD_PROOF_OF_SPACE_STATICALLY=ON ../ \
  && cmake --build . -- -j `nproc`

FROM ubuntu:20.04

WORKDIR /app
COPY --from=builder /app/build/ProofOfSpace /app/

CMD ["/app/ProofOfSpace"]
```

error:
```
docker run -it --rm static-pos  /bin/bash         
root@a0825f17a2d8:/app# ./ProofOfSpace -k 21 -f "plot.dat" -i "7e1392f6b7a2d113f8fb685a7409c81211748c335e87decf348a4345e07dcb2b" create
operation: create
Generating plot for k=21 filename=plot.dat id=7e1392f6b7a2d113f8fb685a7409c81211748c335e87decf348a4345e07dcb2b


Starting plotting progress into temporary dirs: . and .
ID: 7e1392f6b7a2d113f8fb685a7409c81211748c335e87decf348a4345e07dcb2b
Plot size is: 21
Buffer size is: 4608MiB
Using 16 buckets
Final Directory is: .
Using 2 threads of stripe size 65536
Process ID is: 14

Starting phase 1/4: Forward Propagation into tmp files... Tue Jun 15 16:07:58 2021
Computing table 1
Segmentation fault
```

**Pull request merged**
