### PR TITLE
Replace the cerrs which are thrown on CLI with a more b…

### PR DESCRIPTION
**Pull request by Sameeranjoshi**
…etter format.

FORMAT: Error: <short and simple error>: <detailed description>;

### CODE REVIEW

**Comment by Sameeranjoshi** [comment]
Please check 
1. Is this is the correct output of what you want?
2. Also do we need for only `std::cerrs` only ?

You can merge this PR, if it works for you it's independent of the remaining PR's .
We can add more such.

**Comment by SkycoinSynth** [comment]
What is the format? "Error: "?

**Comment by Sameeranjoshi** [comment]
Please check the commit message.
There the format is mentioned.

**Comment by Sameeranjoshi** [comment]
> What is the format? "Error: "?

@SkycoinSynth 
`FORMAT: Error: <short and simple error>: <detailed description>;`

**Comment by Sameeranjoshi** [comment]
This is not WIP not, the other PR completes it.

**Comment by Sameeranjoshi** [comment]
Please merge

**Pull request merged**
